apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  containers:
    - image: jenkins/jenkins:latest
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
  restartPolicy: OnFailure
  volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-home
