apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: roblox-service
  name: roblox-service
spec:
  ports:
    - name: "7102"
      port: 7102
      targetPort: 7102
  selector:
    io.kompose.service: roblox-service
